[package]
name = "firebase-firestore-lite"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"

[build-dependencies]
npm_rs = "0.2"
glob = "0.3"
